# Generated by Django 4.1.5 on 2023-10-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Menu_HotCoffee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu_hotcoffee",
            name="price",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
