# Generated by Django 4.1.5 on 2023-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ContactUs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="subject",
            field=models.CharField(max_length=200),
        ),
    ]
